[package]
name = "winmedic"
version = "0.1.0"
edition = "2021"

[lib]
name = "winmedic_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-store = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["process", "sync", "rt-multi-thread", "fs", "time"] }
reqwest = { version = "0.12", features = ["json", "native-tls"] }
rand = "0.9"
winreg = "0.52"
sysinfo = "0.31"
local-ip-address = "0.6"
tempfile = "3"
chrono = "0.4"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[profile.dev]
incremental = true
